### ISSUE TITLE
Not working in real devices

### ISSUE THREAD

**Issue by yln05091998** [highcharts/highcharts-react-native#101]
Charts is working on emulator devices Android and iOS but when i release file apk and install in my real devices it not rendering. It is my bug?

**Comment by Denyllon** [comment]
Hi @yln05091998 ,

Thank you for report.
We're testing this package in terms of correct work on real devices, also through building standalone and installable applications, and have not seen any errors then. Most probably it is something wrong with your build, but hard to guess without any detail information about your setup.
Are you able to debug the application, and notice some errors in the developer console?
Could you provide us with a minimized demo app/repository, where the problem occurs?

KInd regards!

**Comment by yln05091998** [comment]
> Hi @yln05091998 ,
> 
> Thank you for report.
> We're testing this package in terms of correct work on real devices, also through building standalone and installable applications, and have not seen any errors then. Most probably it is something wrong with your build, but hard to guess without any detail information about your setup.
> Are you able to debug the application, and notice some errors in the developer console?
> Could you provide us with a minimized demo app/repository, where the problem occurs?
> 
> KInd regards!

 It worked in my real android device but still not in iOS( i built ipa file by enterprise account) i see my app can't load layout html. I think it has a problem with function Filesystem or Asset. I used old version(2.x) and my app working perfect. Im using reactCLI. Thanks for supported!

**Comment by Denyllon** [comment]
@yln05091998 I see that you closed the issue. Could you share the info here what was the reason, and how did you resolve it?

**Comment by yln05091998** [comment]
Yes, I used an older version( v2.2.3) and using props useSSL and useDNN for
iOS devices. It's working perfectly. About the issue I think I have
problems with Asset and Filesystem in iOS when using React CLI( not Expo).
Thank you for your support.

Vào Th 4, 2 thg 9, 2020 vào lúc 20:53 Daniel Studencki <
notifications@github.com> đã viết:

**Comment by Denyllon** [comment]
@yln05091998 Thank you for letting us know. Getting back to your problem with v3, have you tried to install `react-native-unimodules` package, and configure them as it is described in [documentation](https://github.com/highcharts/highcharts-react-native#getting-started)?

> In bare Ract Native application you need to also install the react-native-unimodules package, and configure the content of ios and android build directiories like it's described [here](https://docs.expo.io/bare/installing-unimodules/#installation).

**Comment by yln05091998** [comment]
Yes I installed unimodules and configured for Android and iOS , but it only
worked in android devices. I tried to get layoutHtml in parent component in
useEffect with a Loader behind the function getLayout and Loader always is
visible. Thís bug only appears when i ínstall my ipa file so it's hard to
debug.

Vào Th 5, 3 thg 9, 2020 vào lúc 15:28 Daniel Studencki <
notifications@github.com> đã viết:

**Comment by Denyllon** [comment]
@yln05091998 Sorry for the silence here, but the problem is very complicated. I've just left the [comment](https://github.com/highcharts/highcharts-react-native/issues/104#issuecomment-704843709) in the directly related issue, so please take a look on it to get what's happening. Closing this issue to avoid duplicates here.
