### ISSUE TITLE
The chart does not show after packaging

### ISSUE THREAD

**Issue by Tom0115** [highcharts/highcharts-react-native#106]

**Comment by Denyllon** [comment]
Hi @Tom0115 ,

Thank you for contacting us.
Actually, we know about the problem mentioned in the title of this issue, but it's a bit complicated to solve it and do not make regression for certain bugs. Here is the related topic, where you can find a whole discussion about it, and the workaround which might fix the issue, but (most probably) unfortunately if you have only one chart within your app.
https://github.com/highcharts/highcharts-react-native/issues/104

Kind regards!
