### ISSUE TITLE
Support for highmaps

### ISSUE THREAD

**Issue by matiullah-netlinks** [highcharts/highcharts-react-native#111]

**Comment by Denyllon** [comment]
Hi @matiullah-netlinks ,

Thank you for opening the new issue.
Unfortunately the **Maps** module is not supported by this wrapper, and we do not have plans to implement it for now.
Here you can see which modules are supported: https://github.com/highcharts/highcharts-react-native/issues/66#issuecomment-675451391

Kind regards!
