### ISSUE TITLE
showing rangeSelector options

### ISSUE THREAD

**Issue by prasunk96** [highcharts/highcharts-react-native#115]
I wanted to understand if range selector option is available to use or it's not. I tired passing it the way its mentioned on officials doc but it won't render anything.
I also tried to look for potential solutions online but could find any.
this is the option object that i am passing to HighchartsReactNative. the chart renders but the render options don't  load
`chartOptions = {
        title: {
            text: 'FB stock price by minute'
        },
        subtitle: {
            text: 'Using ordinal X axis'
        },
        xAxis: {
            gapGridLineWidth: 0
        },
        rangeSelector: {
            inputPosition: {
                align: 'left',
                x: 0,
                y: 0
            },
            buttonPosition: {
                align: 'right',
                x: 0,
                y: 0
            },
        },
        series: [{
            name: 'FB',
            type: 'area',
            gapSize: 5,
            tooltip: {
                valueDecimals: 2
            },
            fillColor: {
                linearGradient: {
                    x1: 0,
                    y1: 0,
                    x2: 0,
                    y2: 1
                },
                stops: [
                    [0, '#7eb7ed'],
                    [1, 'rgba(126, 183, 237, 0.1)']
                ]
            },
            threshold: null,
            data: [1, 2, 3, 5, 6, 3, 2, 1, 5, 6, 8, 9]
        }]
    }`

**Comment by Denyllon** [comment]
Hi @prasunk96 ,

As the `Highcharts Stock` module is not included into this wrapper, the Range Selector feature is not supported at all.
Here is the list of supported modules: https://github.com/highcharts/highcharts-react-native/issues/66#issuecomment-675451391

Kind regards!
