### ISSUE TITLE
Unable to update series data. 

### ISSUE THREAD

**Issue by cupatil** [highcharts/highcharts-react-native#117]
I am trying to update the data series on the update button by providing new series. As the result, the new series will be a plotting along with the old series.

And After plotting the new series, the values on are X-axis is clear up. Here I Am attaching the code snippet please have look.

Update Function:

`	updateSeries = () => {
		this.setState({ chartOptions: {
		  series: [
			{ 
			  showInLegend: false,
			  color: '#FF0000',
			  data: this.props.data.slice(0, 15),}
		  ]
		} })
	}`

Graph Render code:

`render() {
return (
  <View style={styles.container}>
    <HighchartsReactNative
      styles={styles.chart}
      options={this.state.chartOptions}
    />
    <Button
      title="Refresh"
      onPress={this.updateSeries.bind(this)}/>
  </View>
);
}`

code file: https://gist.github.com/cupatil/da00b0ab0866e3a4f9306f0425e92582

**Comment by Denyllon** [comment]
Hi @cupatil ,

Thank you for the report. I see you've also put your question on StackOverflow, so please continue the thread there. I will test your case as soon as possible.
Here is related link: https://stackoverflow.com/questions/65235495/trying-to-update-high-chart-data?noredirect=1#comment115331178_65235495

Kind regards!

**Comment by cupatil** [comment]
Sure @Denyllon I have also tried the same with the functional component, Series data are updated but not able to plot the graph line properly. Added data series in question also. Please help me out.

**Comment by Denyllon** [comment]
As I mentioned above, please continue the thread on your StackOverflow's question to keep consistency of this topic.
