### ISSUE TITLE
Trigger react native event

### ISSUE THREAD

**Issue by jj-julia** [highcharts/highcharts-react-native#12]
If i have a chart and I tap on one of series item. How do I trigger a react native event where I send through the y value?
Thanks

**Comment by KacperMadej** [comment]
Hi @jj-julia 

This is not a bug nor an enhancement suggestion as far as I can tell, so please contact technical support as advised in the FAQ https://github.com/highcharts/highcharts-react-native#where-to-look-for-help

P.S.
The load event is explained in this code: https://github.com/highcharts/highcharts-react-native#highcharts-live-data-update

Click event for series will be similar and if you want to trigger something on series click using Highcharts API then you could do it there.
API for reference: https://api.highcharts.com/highcharts/series.line.events.click
