### ISSUE TITLE
Customize chart loader

### ISSUE THREAD

**Issue by angeliqueIcono** [highcharts/highcharts-react-native#127]
Hi!
do we have the possibility to customize the graph loader (background + color)?

**Comment by Denyllon** [comment]
Hi @angeliqueIcono ,

Could you tell me which loader do you mean?
Also just wanted to inform that this package is marked as `deprecated` now, so we do not maintain it anymore.

Kind regards!

**Comment by angeliqueIcono** [comment]
I'm very sad to learn that the package is deprecated 😭 ... I was talking about the loader that appears when you put the loader={true} on the component.

**Comment by Denyllon** [comment]
Thank you for explanation.
That loader is nothing else than default Webview's [startInLoadingState](https://reactnative.dev/docs/webview#startinloadingstate). This wrapper only binds this option into a `loader`, and does not have option to customize the appearance of the loader. Actually, it's hard to say it's even possible to do that in any way in Webview.
