### ISSUE TITLE
（HighCharts.dateFormat） How do you use it？

### ISSUE THREAD

**Issue by hxx1197411446** [highcharts/highcharts-react-native#19]
![企业微信截图_157076411522](https://user-images.githubusercontent.com/10133519/66622166-5ec7ca00-ec19-11e9-9e3a-3f10879388c7.png)

**Comment by sebastianbochan** [comment]
Hi @hxx1197411446,
The Highcharts.dateFormat should work like in regular Highcharts.

Did you come across any problems?

**Comment by sebastianbochan** [comment]
The highcharts.js is loaded in Webview (index.html file), so you have an access to Highcharts. Please ensure that you use `Highcharts` instead of `HighCharts`.

**Comment by hxx1197411446** [comment]
Thank you
