### ISSUE TITLE
Hightchart in react native unable to use, please provide steps.

### ISSUE THREAD

**Issue by vnanaware** [highcharts/highcharts-react-native#21]
![Simulator Screen Shot - iPhone 6s Plus - 2019-10-18 at 18 30 25](https://user-images.githubusercontent.com/16416191/67096388-b5af3f80-f1d5-11e9-867b-717fe378028f.png)

**Comment by sebastianbochan** [comment]
Hi @vnanaware,
Thank you reporting. Im closing this issue as duplicate of #8.
