### ISSUE TITLE
Update Webview to use react-native-webview seperately

### ISSUE THREAD

**Issue by hunainaslam** [highcharts/highcharts-react-native#22]
Hi,

Is the work in progress to support this wrapper for react-native > 0.5.9 as `Webview` is not going to be a part of core react-native. I've encountered few issues with the current wrapper if upgraded to use `Webview` as a seperate package including `window.postMessage("Some kind of message");` not working as expected.

Any suggestions?

**Comment by sebastianbochan** [comment]
Hi @hunainaslam,
Thank you for reporting. Im closing the ticket as duplicate of #8.
