### ISSUE TITLE
Can not use in react-native 0.61.1

### ISSUE THREAD

**Issue by CandyKTN** [highcharts/highcharts-react-native#23]
Building Projects with Native Code,react-native 0.61.1 can not use the highcharts-react-native.

**Comment by leonascimento** [comment]
@CandyKTN hi there, I'm following anxiously by this as well.
You should follow these issues. #4 #8 
@sebastianbochan  is working to fix and find a solution to use with the new react-native version that segregated the `react-native-webview` module.

**Comment by sebastianbochan** [comment]
Hi @CandyKTN I guess that your issue is related with two cases (mentioned by @leonascimento ). If yes, please close this ticket as duplicate.

**Comment by CandyKTN** [comment]
Hi @sebastianbochan  I'm not sure,may be the reason.I will close and wait for the next version
