### ISSUE TITLE
Not working if expo published

### ISSUE THREAD

**Issue by zuozhuo** [highcharts/highcharts-react-native#3]
Hi, it's working on `expo start` at local development, but when I build a native iOS or Android bundle as `expo build:ios` or `expo publish`, it does not working

**Comment by zuozhuo** [comment]
It seems that the html file load js or css as relative path, it works when serve on local dev server, but can not reference in published bundle

**Comment by sebastianbochan** [comment]
Hi @zuozhuo,
Thank you for reporting about the bug. I will check it.

**Comment by r-bman** [comment]
It is my understanding that iOS webviews load local static files from an internal local webserver on port 8081. The static file requests look something like `http://localhost:8081/assets/node_modules/@highcharts/highcharts-react-native/highcharts-layout/css/styles.css`. The webview doesn't seem to have access to, or permission to access or execute files in the `node_modules/@highcharts...` directory once the App is compiled.

[I have detailed a solution for ejected Apps here](https://github.com/highcharts/highcharts-react-native/issues/2#issuecomment-500398109)` but I don't know how this can be applied to expo Apps.

**Comment by sebastianbochan** [comment]
@zuozhuo 
Can you test solution of @r-bman and let us know about your results.

**Comment by sebastianbochan** [comment]
The new version (2.0.2) has been already released.

Please test and let me know about your results.

**Comment by axelav** [comment]
has this been resolved? I am using v2.1.1 and am experiencing this issue. everything worked great locally but when the app was published. I get an empty box where the highchart should render.

**Comment by sebastianbochan** [comment]
Have you tried to move files to the correct path (android) -> https://github.com/highcharts/highcharts-react-native#files-are-not-loaded

**Comment by axelav** [comment]
no, this was with an iOS app published with Expo and released through the Apple App Store.

**Comment by r-bman** [comment]
I tested this a little while ago but haven't had chance to comment. I was unable to get the latest version of the library working with local highcharts files on iOS using [this method](https://github.com/highcharts/highcharts-react-native#files-are-not-loaded), which worked previously. I was only able to get the library working when the highcharts files are loaded from the cdn.

**Comment by axelav** [comment]
@r-bman so if you loaded the files from the CDN, did it work in a published app, or just locally when developing? would it be possible for you to show your code of how you configured using the CDN? I'm unclear if it involves more than just passing the `useCDN` prop - ie, what is the CDN URL, which version of highcharts is this loading from CDN, etc?

**Comment by r-bman** [comment]
I haven't published an App using this library so I'm afraid I can't help you there. I think I just set the `useCDN` prop to true, yes. You can see what the `useCDN` prop does in [HighchartsReactNative](https://github.com/highcharts/highcharts-react-native/blob/master/dist/src/HighchartsReactNative.js). I opted not to use this library in the end, in favour of a custom solution which is not currently published.

**Comment by axelav** [comment]
@r-bman gotcha, thanks for that info!

**Comment by sebastianbochan** [comment]
It can be related with the issue react-native-community/react-native-webview#875, Im waiting for a feedback from users about that.

**Comment by axelav** [comment]
any further info on this one?

**Comment by sebastianbochan** [comment]
At this moment all problems are combined and described here: https://github.com/highcharts/highcharts-react-native/issues/39 (also including some fixes).
