### ISSUE TITLE
Please add option for adding styles directly to WebView

### ISSUE THREAD

**Issue by JustynaKK** [highcharts/highcharts-react-native#36]
I would like to be able to pass styles or at least background prop directly to WebView to add backgroundColor: 'transparent'. Without that webview is white, which overriding my color set up for view.
Setting bg color directly to chart.options changing only the color of the chart area, not the whole webview container.

![80266060_602520110496089_3574863733303803904_n](https://user-images.githubusercontent.com/35225853/70923878-03da9680-1fff-11ea-885f-699bd32defe4.jpg)

**Comment by sebastianbochan** [comment]
Than you for the suggestion, will check the solution.

**Comment by 77xi** [comment]
Hi @JustynaKK webviewStyles has added in `highcharts-react-native ^2.1.1 `https://github.com/highcharts/highcharts-react-native#webviewStyles
