### ISSUE TITLE
Column Chart with only negative values does not render

### ISSUE THREAD

**Issue by JarnaKantaria** [highcharts/highcharts-react-native#37]
Is this a bug? the chart doesn't seem to render. 

Data I am trying to render - 
[{
                        name: 'John',
                        data: [-170629.76639999845, -120629.76639999845, -124629.76639999845, -111629.76639999845, -156629.76639999845]
                    }, {
                        name: 'Jane',
                        data: [-170629.76639999845, -170629.76639999845, -170629.76639999845, -170629.76639999845, -170629.76639999845]
                    }, {
                        name: 'Joe',
                        data:[-100629.76639999845, -1700629.76639999845, -10629.76639999845, -190629.76639999845, -100629.76639999845]
                    }];

**Comment by sebastianbochan** [comment]
Hi @JarnaKantaria,
Thank you for reporting the bug. Have you tried to set the min / max value on yAxis?

Im in process of upgrading of v8, so will check this case too.

**Comment by JarnaKantaria** [comment]
Hi @sebastianbochan,

No, My yAxis looks like this,

yAxis: {
                title: {
                    text: yAxisPrimaryText ? yAxisPrimaryText : ""
                },
                stackLabels: {
                    enabled: false,
                }
            },

Current version that I am using - 
"@highcharts/highcharts-react-native": "^2.0.3"


When is the upgrade planned? We have a release lined up actually.
Any temporary hotfix I can do in the library for now?

**Comment by sebastianbochan** [comment]
Please try to set min / max values or dynamic values by tickPositioner.

All options are documented in our docs here:
- https://api.highcharts.com/

Let me know about results.

**Comment by JarnaKantaria** [comment]
Extremely sorry for the delayed response. 
There was some data formatting issue for this chart, thus not accepting negatives.

**Comment by sebastianbochan** [comment]
I suspect that the issue is solved. Can I close the ticket?

**Comment by JarnaKantaria** [comment]
Sure yes :)
Thank you
