### ISSUE TITLE
Highcharts - not displaying in android?

### ISSUE THREAD

**Issue by techmangokarthik** [highcharts/highcharts-react-native#46]
Hi Team,

Thanks for the excellent graph solution.

I m using for one of RN apps - iOS is working great - Android is not displaying with shows "Error  Loading Page .

dependencies : 
"@highcharts/highcharts-react-native": "^2.1.1"
"react": "16.9.0",
 "react-native": "0.61.4",

Thanks

![android](https://user-images.githubusercontent.com/43411211/72235174-9ec29280-35f6-11ea-875f-3c4da161c2b9.png)

**Comment by techmangokarthik** [comment]
followed the copy files in assets / android folder . - working fine. Thanks

**Comment by sebastianbochan** [comment]
Thank you for the feedback!
