### ISSUE TITLE
Background color of webview body is always white

### ISSUE THREAD

**Issue by linelson** [highcharts/highcharts-react-native#47]
The background color of the webview 'body' element is always white.
https://github.com/highcharts/highcharts-react-native/issues/36 is related, but the suggested fix does not work.Providing a background color via the webviewStylesProp does not solve this issue because it is the background color for the html rendered in the webview that is the problem. 
Ideally, there would be a way to provide a body background color for the HTML rendered in the webview.

Sample screenshot:
![image](https://user-images.githubusercontent.com/33672730/74295508-1a972400-4cf6-11ea-9422-2494e03ed1f8.png)

**Comment by sebastianbochan** [comment]
Hi @linelson,
Thank you for reporting about the problem. It looks like webView applies the white color by default. The solution is set the `backgroundColor` as transparent and then apply container styles.

Demo:
```
                <HighchartsReactNative
                    styles={styles.container}
                    options={this.state.chartOptions}
                    webviewStyles={{backgroundColor: 'transparent'}}
                />
```

styles:

```
const styles = StyleSheet.create({
    container: {
        justifyContent: 'center',
        backgroundColor: 'orange'
    },
    button: {
        justifyContent: 'center'
    }
});
```
If the chart should be also transparent, you need to declare it in the the `chartOptions.chart.backgroundColor: 'red'`.

```
this.state = {
            chartOptions: {
                series: [{
                    name: 'Speed',
                    data: [1, 10, 3]
                }],
                chart: {
                    
                    type: 'line'
                }
            }
        };
```

**Comment by linelson** [comment]
Thanks for the fast response! This works.
I realized that I made a silly error - I incorrectly capitalized the webviewStyles prop to webViewStyles, which was causing them not to be applied.
Apologies for opening an issue for my mistake.

**Comment by sebastianbochan** [comment]
You're welcome.
