### ISSUE TITLE
Unable to use custom imported font for legend and axis title (iOS)

### ISSUE THREAD

**Issue by amankarora** [highcharts/highcharts-react-native#49]
I have been trying to integrate my own custom font that is used throughout my app in the Highcharts but it does not recognise it. I have been unable to locate an example of where someone has used a custom font in their application without it being hosted externally. The .TTF file of the font is in my project folder and loaded asynchronously in my App.js. It would be much appreciated if someone could provide some guidance or if this feature could be added to the project.

**Comment by sebastianbochan** [comment]
Hi @amankarora,
Let me know if font is available online or loaded from local file system?

**Comment by sebastianbochan** [comment]
Hi @amankarora,
Have you tried to use 

```
chartOptions = {
   title: {
    style: {
      color: '#000',
      fontFamily: 'Oswald, sans-serif' // you font name
    }
  },

  series: [{
    data: [71.5, 106.4, 129.2, 176.0, 135.6, 148.5, 216.4, 194.1, 54.4]
  }]
}
```

**Comment by amankarora** [comment]
Hi @sebastianbochan 

Thank you for the reply, yes I have however instead of becoming my font, it changes it to another style. Im not sure if that's because it is not being recognised by Highcharts correctly because the font works correctly throughout the rest of the app. Does Highcharts require the font to be in a particular format? 

If you see the image below, I want the y axis font to be the same as the font of the numbers at the top. However it is changing to a completely different style. 

![Image from iOS (2)](https://user-images.githubusercontent.com/43746775/74644296-fd3add80-516d-11ea-87aa-2dec12ca2ce9.png)

Inside the `chartOption` I am configuring the `yAxis` and as you can see I am using my custom font in the style section but it not being recognised 
```yAxis: {
          crosshair: false,
          opposite: false,
          title: {
            enabled: false
          },
          offset: -24,
          showLastLabel: true,
          showFirstLabel: true,
          maxPadding: 0.02,
          gridLineColor: "#3a3a3a",
          lineColor: "#3a3a3a",
          tickPixelInterval: 100,
          labels: {
            // formatter: function() {
            //   return props.yAxisValueFormat(this.value);
            // },
            align: "left",
            y: -3,
            x: 0,
            style: {
              fontSize: 12,
              color: "rgba(255,255,255,0.8)",
              userSelect: "none",
              fontFamily: "Mark-Bold"
            }
          },
          lineWidth: 0
        },
```

Do I need to import it in a particular way?

**Comment by sebastianbochan** [comment]
You should add fonts in a proper way, which is described in our iOS wrapper docs. 

https://github.com/highcharts/highcharts-ios (the custom font chapter)

**Comment by amankarora** [comment]
Thanks for that but I am using React Native and Expo for my project. Is there any other way you could suggest?

**Comment by sebastianbochan** [comment]
Yes I aware of that, but react native also "translate your application" to native iOS. So you need to add the font to iOS application's system. Please try to add the font like in mentioned link (not using iOS wrapper).

**Comment by sebastianbochan** [comment]
@amankarora do you use EXPO CLI app or native React Native CLI?

**Comment by confusingbits** [comment]
I'm experiencing a similar issue on a project. This one is an ejected app with native code. We have imported a font, into the app and they work everywhere else but in high charts rn.

@sebastianbochan If possible, would you explain in more detail how to add fonts that will be visible to HCRN? Assuming only basic native knoweldge, like linking and hooking up native RN modules in AppDelegate/MainActivity? Thanks :)

**Comment by sebastianbochan** [comment]
Hi @confusingbits, 
Have you tried to to place the font in a proper directory (like in my comment above) ?

**Comment by sebastianbochan** [comment]
Closed due to inactivity.

**Comment by amirsabanovic** [comment]
> @amankarora do you use EXPO CLI app or native React Native CLI?

Will this work in an Expo Managed Workflow (using expo-cli)?

**Comment by sebastianbochan** [comment]
The issue was related to previous version of wrapper (<3.0). Please let me know if you have still a problem with it.

**Comment by amirsabanovic** [comment]
> The issue was related to previous version of wrapper (<3.0). Please let me know if you have still a problem with it (in the newest release).

I am on `3.1.2`, the issue persists.

**Comment by sebastianbochan** [comment]
I will try to debug it as soon as possible.
