### ISSUE TITLE
running on expo returned response error code 500

### ISSUE THREAD

**Issue by danaccion** [highcharts/highcharts-react-native#54]
![88197330_636209543833199_8829330515686326272_n](https://user-images.githubusercontent.com/31457124/75214449-9601d680-57c8-11ea-8ec6-1f02c1690554.png)

**Comment by sebastianbochan** [comment]
Hi @danaccion,
It looks like problem with your dev expo environment, not the wrapper. I suggest you to contact with Expo developers.
