### ISSUE TITLE
how to import example to React-native

### ISSUE THREAD

**Issue by JongGyuChoi** [highcharts/highcharts-react-native#57]
i wanted to implement below chart in React-native 

[https://jsfiddle.net/5s09z4Lg/](url)
![Screen Shot 2020-03-03 at 7 50 34 PM](https://user-images.githubusercontent.com/33406511/75774605-a64f1e00-5d93-11ea-9b1c-caf2ff0aee2d.png)
![Screen Shot 2020-03-03 at 7 50 50 PM](https://user-images.githubusercontent.com/33406511/75774607-a94a0e80-5d93-11ea-8797-f86e1cbbbf89.png)

i was use webView and injectjavasciprt but jquery code has not worked

somebody help me plz

**Comment by sebastianbochan** [comment]
Hi @JongGyuChoi,
Could you elaborate your question? 

In case when you download the github repo, you can run the example as expo application.
