### ISSUE TITLE
Is this library Typescript supported?

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts-react-native#6]

**Comment by KacperMadej** [comment]
Hi @SaeedZhiany 

Thank you for contacting us about the problem.

For questions and problems with the wrapper please contact Highcharts technical support as suggested [here](https://github.com/highcharts/highcharts-react-native#where-to-look-for-help).

tl;dr: No, do you want it to?

**Comment by SaeedZhiany** [comment]
Hi @KacperMadej 
Thank you for your response, unfortunately, I don't have enough time to do it right now.
I'm closing this issue.
