### ISSUE TITLE
Error loading page Domain :undefined Error Code:-1 Description:net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by 112200369** [highcharts/highcharts-react-native#64]
After the introduction of highcharts component according to the official package introduction of highcharts react native, I did not display the expected chart report in my project, which is a big help man!

Error loading page Domain :undefined Error Code:-1 Description:net::ERR_FILE_NOT_FOUND

**Comment by 112200369** [comment]
> After the introduction of highcharts component according to the official package introduction of highcharts react native, I did not display the expected chart report in my project, which is a big help man!
> 
> Error loading page Domain :undefined Error Code:-1 Description:net::ERR_FILE_NOT_FOUND

**Comment by akiladevinda** [comment]
Hi have you solved this issue ?

**Comment by sebastianbochan** [comment]
The issue is duplicate of https://github.com/highcharts/highcharts-react-native/issues/51
