### ISSUE TITLE
How to use map module?

### ISSUE THREAD

**Issue by kdenz** [highcharts/highcharts-react-native#66]
```js
<HighchartsReactNative
        useCDN={true}
        useSSL={true}
        styles={chartStyles}
        options={chartOptions}
        modules={['map']}
      />
```
It doesn't work like this, any clue? @sebastianbochan  thanks~

For the options I'm using exactly what worked for highcharts react web

```js
export const getChartOptions = ({
  // formatNumber,
  // currency,
  data,
  height,
}: AreaChartOptions) => {
  return {
    exporting: {
      enabled: false,
    },
    title: {
      text: '',
    },
    chart: {
      height,
      borderRadius: rd('xSmall'),
      backgroundColor: '#f8f8f9',
      style: {
        fontFamily: '"Montserrat", sans-serif',
      },
    },
    plotOptions: {
      map: {
        states: {
          hover: {
            color: '#EEDD66',
          },
        },
      },
    },
    colorAxis: {
      minColor: 'rgba(34,92,116,0.20)',
      maxColor: '#225C74',
      labels: {
        enabled: true,
        style: {
          fontSize: 13,
        },
      },
    },
    tooltip: {
      // formatter: function () {
      //   return (
      //     this.point.name +
      //     ': ' +
      //     formatNumber(this.point.value, {style: 'currency', currency})
      //   );
      // },
    },
    legend: {
      enabled: data.length > 0,
      align: 'right',
      verticalAlign: 'bottom',
    },
    series: [
      {
        animation: false,
        mapData: worldContinentData,
        joinBy: 'hc-key',
        data,
        dataLabels: {
          enabled: true,
          format: '{point.name}',
        },
      },
    ],
    mapNavigation: {
      enabled: false,
      buttonOptions: {
        verticalAlign: 'bottom',
      },
    },
  };
};
```

**Comment by kdenz** [comment]
I'm getting this
![image](https://user-images.githubusercontent.com/12795428/78387535-19a5b300-7612-11ea-845a-7493433b7aac.png)

**Comment by sebastianbochan** [comment]
Hi @kdenz,
Would you like to use the module: https://code.highcharts.com/maps/modules/map.js ? At this moment highmaps are not supported, so this module is also not valid.

**Comment by shrikantr-iprogrammer** [comment]
Hi @sebastianbochan , Please let us know the list of all supported modules.

**Comment by ShrikantRao** [comment]
Hi @sebastianbochan  , Please let us know the list of all supported modules.

**Comment by epfromer** [comment]
Are Chord and Network Graph modules supported for Native?

**Comment by Denyllon** [comment]
@ShrikantRao, @epfromer,  here is the list of the modules which should work without any problems:

- boost
- boost-canvas
- bullet
- coloraxis
- cylinder
- dependency-wheel
- dotplot
- drilldown
- dumbbell
- exporting
- full-screen
- funnel
- funnel3d
- heatmap
- histogram-bellcurve
- item-series
- lollipop
- networkgraph
- no-data-to-display
- organization
- parallel-coordinates
- pareto
- pattern-fill
- pyramid3d
- sankey
- series-label
- solid-gauge
- streamgraph
- sunburst
- tilemap
- timeline
- treegrid
- variable-pie
- variwide
- vector
- venn
- windbarb
- wordcloud
- xrange
