### ISSUE TITLE
Boost module

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts-react-native#69]
The boost module seems to not working.

**Comment by sebastianbochan** [comment]
Closed by commit https://github.com/highcharts/highcharts-react-native/commit/f58d39bf61aabab8252a0597a649c25cb95447eb

Use 'boost' in modules object.

```
const modules = [
    'boost'
];
```

**Comment by girish54321** [comment]
Can You plz tell me how to import this 

`import Boost from "@highcharts/highcharts-react-native/boost"; ` ????

**Comment by sebastianbochan** [comment]
You should use the construction 

```
const modules = [
    'boost'
];
```

This is the only proper way.

**Comment by girish54321** [comment]
Thanks @sebastianbochan .
