### ISSUE TITLE
Getting a already solved error

### ISSUE THREAD

**Issue by Niravpatel129** [highcharts/highcharts-react-native#71]
https://github.com/highcharts/highcharts-react-native/issues/30 

My Versions:
    "@highcharts/highcharts-react-native": "^2.2.0",
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^9.2.2"

Getting the exact same error as above

**Comment by amirsabanovic** [comment]
I am also getting this error, so what happened here that made you close the issue right away?

**Comment by amirsabanovic** [comment]
> I am also getting this error, so what happened here that made you close the issue right away?

Okay, nevermind, I figured it out. For anyone wondering, it is necessary to specify _at least_ the `height` inside the `styles` prop of the `HighchartsReactNative` element, as it gets assigned to `userStyles` in the wrapper code.
