### ISSUE TITLE
Chart Update pattern does not work for basic bar while trying to change the no. of bars displayed for each category

### ISSUE THREAD

**Issue by astron97** [highcharts/highcharts-react-native#72]
Say for example I have basic bar chart where each category has three bars, If i try changing these from three to two bars the chart simply shows the initial three bars whilst able to update individual y values.
![Screenshot_2020-04-29-16-49-59-1145623991](https://user-images.githubusercontent.com/45058613/80590590-ce789780-8a39-11ea-83d9-d8b19fba3067.png)
the source of data is like this following screenshot:
Am adding and removing the objects from array.
![image](https://user-images.githubusercontent.com/45058613/80590739-0da6e880-8a3a-11ea-87c3-3a99d9588329.png)
the update pattern is like the below screenshot:
![image](https://user-images.githubusercontent.com/45058613/80591043-9a51a680-8a3a-11ea-9ba7-6234edeb7d4c.png)
the optionsSwitcher() is called in componentDidUpdate which logs the updated series array whereas the chart does not show the change in no. of bars.

_Originally posted by @astron97 in https://github.com/highcharts/highcharts-react-native/issues/59#issuecomment-621143823_

**Comment by sebastianbochan** [comment]
The issue was caused by missing "oneToOne" param in `chart.update()`.

Fixed the issue in 2.2.1 version.

Please test and reopen when new issues will come.
