### ISSUE TITLE
Highcharts not rendering but "Chart title" and highcharts label displays.

### ISSUE THREAD

**Issue by jgeliberte** [highcharts/highcharts-react-native#75]
i tried doing the sample code and implement the changes for the web view of react native and i was able to do it properly (moving the highcharts folders to android/app/src/main/assests).

The problem is when i tries to load the graph it only shows the "Chart title" and highcharts indicator at the bottom right corner of the screen. 
There is no error showing so i was wondering what could be the problem.

![96026007_3700300423377365_108992435882819584_n](https://user-images.githubusercontent.com/11845939/81064032-81019c00-8f0b-11ea-8b77-2007ef3c280d.jpg)

here is the image of the highcharts section on my android device.
im running :

    "@highcharts/highcharts-react-native": "^2.2.1",
    "react": "^16.13.1",
    "react-base": "^0.2.0",
    "react-native": "0.61.0",
    "react-native-webview": "^9.4.0",

**Comment by sebastianbochan** [comment]
Could you share your chart's options (including data) ?

**Comment by jgeliberte** [comment]
> Could you share your chart's options (including data) ?

I used the one in the guide.

```
<HighchartsReactNative
                    styles={styles.container}
                    options={this.state.chartOptions}
                />
```

and for the data

```
{
            chartOptions: {
                series: [{
                    data: [1, 2, 3]
                }]
            }
        };
```

**Comment by lucasnovelo** [comment]
> > Could you share your chart's options (including data) ?
> 
> I used the one in the guide.
> 
> ```
> <HighchartsReactNative
>                     styles={styles.container}
>                     options={this.state.chartOptions}
>                 />
> ```
> 
> and for the data
> 
> ```
> {
>             chartOptions: {
>                 series: [{
>                     data: [1, 2, 3]
>                 }]
>             }
>         };
> ```

Try to add useCDN option

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
