### ISSUE TITLE
SetOptions for chart doesn't work

### ISSUE THREAD

**Issue by Ikaarou** [highcharts/highcharts-react-native#77]
Hello,
I needed to update the language of the charts using the setOptions that you provided, but it didn't work.

I ended up investigating and I may have find the solution 
` Highcharts.setOptions('${setOptions}');` is trying to add [Object object] to highcharts options
I fixed it locally with
`Highcharts.setOptions(${JSON.stringify(setOptions)});`

I don't know if that can be a breaking changes for other users but it worked for me.

**Comment by sebastianbochan** [comment]
Hi @Ikaarou,
Thank you for suggestion, but have you tried to use the official way: https://github.com/highcharts/highcharts-react-native#setOptions ? Does it work properly in you app or not?

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
