### ISSUE TITLE
Android: erorr loading page. Domain: undefined

### ISSUE THREAD

**Issue by MaximMalyavko85** [highcharts/highcharts-react-native#81]
Also i create new expo project.
Downloaded @highcharts/highcharts-react-native.
Set build.gradle, how pointed top, relocated 2 folders, how pointed top.
And geted same problem:
Encountered an error loading page, Object {
"canGoBack": false,
"canGoForward": false,
"code": -1,
"description": "net::ERR_FILE_NOT_FOUND",
"loading": false,
"target": 3,
"title": "",
"url": "file:///android_asset/highcharts-layout/index.html",
}

I appeal to contributors @highcharts/highcharts-react-native.
Team, help me. Why i geted this problem. In resources i am not getting answer for this question.
Many developers getting errors?
This issue not duplicating same issues. I am not getting answered by my question.
This is bug?

**Comment by otikindriyana** [comment]
same issue :(

**Comment by sebastianbochan** [comment]
Hi @otikindriyana,
Thank you for reporting. The issue is duplicate of https://github.com/highcharts/highcharts-react-native/issues/51#issuecomment-634117445
