### ISSUE TITLE
Unable to set `backgroundColor` due to old version of `react-native-webview`

### ISSUE THREAD

**Issue by chandlervdw** [highcharts/highcharts-react-native#82]
Currently, this package utilizes [`react-native-webview: ^5.12.0`](https://github.com/highcharts/highcharts-react-native/blob/master/package.json#L40) but a bug existed before [version 7.1.0](https://github.com/react-native-community/react-native-webview/releases/tag/v7.1.0) that prevents alteration of the `backgroundColor` for the webview from `#ffffff`.

The latest release is [`v10.2.3`](https://github.com/react-native-community/react-native-webview/releases/tag/v10.2.3). Could we get a package update?

**Comment by sebastianbochan** [comment]
Thank you for the input, I will update it this week.

**Comment by sebastianbochan** [comment]
The new 3.0 version is released. 

Im closing this ticket. If you will encounter any problems, please create a new ticket. In this case we will avoid confusing and keep the newest version on track.
