### ISSUE TITLE
setOptions source review please

### ISSUE THREAD

**Issue by shinseon89** [highcharts/highcharts-react-native#84]
I think it should be changed as below to specify a setting value for the setOption property, can you review it?

before
`                    if (redraw) {
                        Highcharts.setOptions('${setOptions}');
                        Highcharts.chart("container", ${this.serialize(this.props.options)});
                    }
`

after
`                    if (redraw) {
                        Highcharts.setOptions(${this.serialize(setOptions)});
                        Highcharts.chart("container", ${this.serialize(this.props.options)});
                    }
`

**Comment by pawelfus** [comment]
Thanks for reporting the issue @shinseon89 

FYI @sebastianbochan
