### ISSUE TITLE
Error: Failed to compile

### ISSUE THREAD

**Issue by ImToxicCode** [highcharts/highcharts-react-native#85]
Failed to compile.
node_modules/@highcharts/highcharts-react-native/src/HighchartsReactNative.js 160:15
Module parse failed: Unexpected token (160:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|         // Create container for the chart
>         return <View style={[
|             this.props.styles,
|             { width: this.state.width, height: this.state.height }, height: this.state.height }

**Comment by sebastianbochan** [comment]
Hi @ImToxicCode,
Could you paste an example of your simplified app?

**Comment by sebastianbochan** [comment]
The new 3.0 version is released. 

Im closing this ticket. If you will encounter any problems, please create a new ticket. In this case we will avoid confusing and keep the newest version on track.
