### ISSUE TITLE
Can't render the chart on Android

### ISSUE THREAD

**Issue by rahulxxarora** [highcharts/highcharts-react-native#86]
Hi, thanks for giving us this awesome library.

I have been trying to use this to render a chart on Android. I have seen the issue #51 and copied both the folders in my android's assets folder.

I even used this sample code from the docs:

```
import React from 'react';
import {
    StyleSheet,
    WebView,
    Text,
    View,
    Button
} from 'react-native';
import HighchartsReactNative from '@highcharts/highcharts-react-native'

export default class App extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            chartOptions: {
                series: [{
                    data: [1, 2, 3]
                }]
            }
        };
    }

    render() {
        return (
            <View>
                <HighchartsReactNative
                    styles={styles.container}
                    options={this.state.chartOptions}
                />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#fff',
        justifyContent: 'center'
    }
});
```
After doing all this, I still can't render the chart on Android. Could you please tell me what am I doing wrong here?

**Comment by harryli8725** [comment]
neither am I

**Comment by huyhai** [comment]
same

**Comment by epfromer** [comment]
same

**Comment by sebastianbochan** [comment]
We are wokring on that and debugging the problem. Can be related with new versions of modules.

Thankfully, we are able to reproduce the problem.

I will inform you about progress, when find a reason of issue.

**Comment by gauravrami** [comment]
Hi @sebastianbochan ,

**Any updates on this?**

**Comment by sebastianbochan** [comment]
We are testing and the beta version should be available on Monday (27.07).

**Comment by gauravrami** [comment]
> We are testing and the beta version should be available on Monday (27.07) (all depends on final tests result)

Yeah.. waiting for it. Thank you so much.

**Comment by sebastianbochan** [comment]
We just finished testing the wrapper and released the beta version which is available here https://github.com/highcharts/highcharts-react-native/tree/beta-3

Any feedback will be really helpful.

Please keep in mind, that all packages should be in the latest versions of them. Number of versions are declared also in the `package.json` file.

**Comment by gauravrami** [comment]
Hi @sebastianbochan , 
Thank you for the beta release. but I am not able to install the same. I don't know I am doing a silly mistake or something else. Please check below is error while installing beta version.

`npm install https://github.com/highcharts/highcharts-react-native/tree/beta-3`
Error Log:
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/highcharts/highcharts-react-native/tree/beta-3'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v14.6.0
4 verbose npm-session ef7cdd875b488470
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://github.com/highcharts/highcharts-react-native/tree/beta-3 838ms
8 silly fetchPackageMetaData error for https://github.com/highcharts/highcharts-react-native/tree/beta-3 Non-registry package missing package.json: https://github.com/highcharts/highcharts-react-native/tree/beta-3.
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 3450ms
11 verbose stack Error: Non-registry package missing package.json: https://github.com/highcharts/highcharts-react-native/tree/beta-3.
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/finalize-manifest.js:157:23
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
11 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
11 verbose stack     at Promise.eval (eval at thenCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
11 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
11 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
11 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
11 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at processImmediate (internal/timers.js:458:21)
12 verbose cwd /Volumes/DATA-D/GauravRami/Projects/Alorica_V2/GIT/AloricaDGA
13 verbose Darwin 19.6.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/highcharts/highcharts-react-native/tree/beta-3"
15 verbose node v14.6.0
16 verbose npm  v6.14.6
17 error code ENOPACKAGEJSON
18 error package.json Non-registry package missing package.json: https://github.com/highcharts/highcharts-react-native/tree/beta-3.
19 error package.json npm can't find a package.json file in your current directory.
20 verbose exit [ 1, true ]
`

**Comment by sebastianbochan** [comment]
The beta version is not available on npm, only by github branch.

**Comment by epfromer** [comment]
I am trying to install this branch, but getting an error.  

`PS D:\github\X2ReactNative> yarn add https://github.com/highcharts/highcharts-react-native.git#beta-3
yarn add v1.22.4
[1/4] Resolving packages...
error Can't add undefined: invalid package version undefined.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
PS D:\github\X2ReactNative> `

**Comment by sebastianbochan** [comment]
The new 3.0 version is released. 

Im closing this ticket. If you will encounter any problems, please create a new ticket. In this case we will avoid confusing and keep the newest version on track.
