### ISSUE TITLE
unexpected alerts in highcharts-layout

### ISSUE THREAD

**Issue by wingkwong** [highcharts/highcharts-react-native#87]
```
"@highcharts/highcharts-react-native": "^2.2.2",
```

Line 49 - 50
```
alert('a')
alert(Highcharts);
```

node_modules/@highcharts/highcharts-react-native/highcharts-layout/index.html

```html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0" />
	<link rel="stylesheet" type="text/css" href="css/styles.css">
    <script>
		const hcUtils = {
		    // convert string to JSON, including functions.
		    parseOptions: function (chartOptions) {
		        const parseFunction = this.parseFunction;

		        const options = JSON.parse(chartOptions, function (val, key) {
		            if (typeof key === 'string' && key.indexOf('function') > -1) {
		                return parseFunction(key);
		            } else {
		                return key;
		            }
		        });

		        return options;
		    },
		    // convert funtion string to function
		    parseFunction: function (fc) {

		        const fcArgs = fc.match(/\((.*?)\)/)[1],
		            fcbody = fc.split('{');

		        return new Function(fcArgs, '{' + fcbody.slice(1).join('{'));
		    }
		};

		// Communication between React app and webview. Receive chart options as string.
		document.addEventListener('message', function (data) {
		    Highcharts.charts[0].update(
				hcUtils.parseOptions(data.data),
				true,
				true,
				true
			);
		});

		window.addEventListener('message', function (data) {
		    Highcharts.charts[0].update(
				hcUtils.parseOptions(data.data),
				true,
				true,
				true
			);
		});
alert('a')
		alert(Highcharts);
   	</script>
  </head>
  <body>
  	<div id="container"></div>
  </body>
</html>

```

**Comment by sebastianbochan** [comment]
Do you use the master branch? When I open https://github.com/highcharts/highcharts-react-native/blob/master/dist/highcharts-layout/index.html I do not see these lines.

**Comment by wingkwong** [comment]
@sebastianbochan I also checked this file and didn't see it. However, when I yarn add ``@highcharts/highcharts-react-native``, it comes with these alerts. I didn't specific which branch when I run yarn. I guess it should be master? One possible reason may be like the author added debug code on local and deployed to npm without removing them.

**Comment by sebastianbochan** [comment]
The npm uses master branch, so Im not sure how its possible.

Will update the version on npm to 2.2.3, only for re-release the master. Maybe something went wrong somewhere.

**Comment by Denyllon** [comment]
Hi @wingkwong 

You were totally right. There was the difference between NPM published version, and `master` branch.
The code now has been made consistent between those two sources, and the version increased to `v.2.2.3`, so you can simply update the package, and the problem will be resolved.

Kind regards!
