### ISSUE TITLE
Unable to resolve "../highcharts-files/highcharts.hcscript"

### ISSUE THREAD

**Issue by epfromer** [highcharts/highcharts-react-native#93]
I am following the blog post at [https://www.highcharts.com/blog/post/creating-mobile-charts-with-highcharts-react-native/](url) but am getting the following error when I connect with Expo:

`Failed building JavaScript bundle.
Unable to resolve "../highcharts-files/highcharts.hcscript" from "node_modules\@highcharts\highcharts-react-native\src\HighchartsModules.js"`

My dependencies are:

```
    "@highcharts/highcharts-react-native": "^3.0.1",
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-unimodules": "^0.10.1",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^9.4.0"
```

**Comment by epfromer** [comment]
Apologies, I didn't see the new instructions to add the .hcscript into the asset extensions section of metro.config.js.  I did that, and the app launches, but on iOS I just get blank screen with the basic example.

**Comment by sebastianbochan** [comment]
Are you able to share your app ? Do you use ejected expo or native expo?

**Comment by epfromer** [comment]
Sure, it's here: https://github.com/epfromer/foo

Native expo I believe (I haven't ejected it).

**Comment by sebastianbochan** [comment]
Hi @epfromer,
Thank you for demo, I will debug it and get back to you, tomorrow.

**Comment by sebastianbochan** [comment]
Hi @epfromer,
I debugged your code and it looks like the  `alignItems: 'center'` style breaks the `View`.

**Comment by epfromer** [comment]
Just confirmed you are right - not sure why.  Anyway, thanks for the help.

**Comment by Joshuaasare** [comment]
Hi @epfromer  how were you able to add the hcscript file?

**Comment by sebastianbochan** [comment]
You should add / edit your metro file.

Please check our docs here: https://github.com/highcharts/highcharts-react-native#installing

**Comment by epfromer** [comment]
I have a monorepo with Yarn Workspaces, which also requires editing the metro config file.  I added the hscript asset this way:

```
const { createMetroConfiguration } = require('expo-yarn-workspaces')
const config = createMetroConfiguration(__dirname)
config.resolver.assetExts = [...config.resolver.assetExts, 'hcscript']
module.exports = config
```

**Comment by Joshuaasare** [comment]
<img width="621" alt="Screenshot 2020-08-18 at 1 07 40 PM" src="https://user-images.githubusercontent.com/35935615/90516676-df1d5c80-e153-11ea-9098-fe816ff64b17.png">

That's my metro config file, i added it just like the docs recommend but still getting this error

**Comment by sebastianbochan** [comment]
What kind of error ? About missing `.hcscript`? Do you have metro-config package?

**Comment by abhiburk** [comment]
Even after using metro config file code I get 
```
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```
