### ISSUE TITLE
expo-filesystem.downloadasync is not available on android

### ISSUE THREAD

**Issue by wzhang2** [highcharts/highcharts-react-native#96]
the charts show up ok on iOS, but when it gets to android, I found out that the rendering would always return an empty View cause the hcModulesReady flag is false

` render() {
        if (this.state.hcModulesReady) {
            const scriptsPath = this.state.useCDN ? httpProto.concat(cdnPath) : path;
            const setOptions = this.state.setOptions;
          ...
            // Create container for the chart
            return (
                <View
                    style={[
                        this.props.styles,
                        { width: this.state.width, height: this.state.height }
                    ]}
                >
                    <WebView
                        ref={ref => { this.webviewRef = ref }}
                        onMessage={this.props.onMessage ? (event) => this.props.onMessage(event.nativeEvent.data) : () => { }}
                        source={
                            {
                                html: this.state.layoutHTML
                            }
                        }
                        injectedJavaScript={runFirst}
                        originWhitelist={["*"]}
                        automaticallyAdjustContentInsets={true}
                        allowFileAccess={true}
                        javaScriptEnabled={true}
                        domStorageEnabled={true}
                        useWebKit={true}
                        scrollEnabled={false}
                        mixedContentMode='always'
                        allowFileAccessFromFileURLs={true}
                        startInLoadingState={this.props.loader}
                        style={this.props.webviewStyles}
                    />
                </View>
            )
        } else {
            return <View></View>
        }
    }`

I tried to copy the Highcharts-files and Highcharts-layout folders to android/app/src/main/assets/ and run the release build, but it still wouldn't work

I'm using a functional component instead of a HOC, and I'm using android product flavours, im not sure if any of these would make a difference, here's my rendering logic

` <View>
<HighchartsReactNative
         styles={lineChartStyles.container}
                options={chartOptions} />
        </View>`

i tried to render the examples from the doc and to no avail as well

my versions are:
"react": "16.8.6"
"react-native": "0.60.5"
"@highcharts/highcharts-react-native": "^3.0.1"
"react-native-webview": "^10.4.1"
"metro-config": "^0.62.0"

node -v
v12.9.1
npm -v
6.10.3

im not using expo, and i tried this on both simulators and actual devices

**Comment by wzhang2** [comment]
<img width="403" alt="Screenshot 2020-08-13 at 6 05 29 PM" src="https://user-images.githubusercontent.com/33023695/90122475-e9c0a600-dd8f-11ea-816e-85597c459c2e.png">
<img width="358" alt="Screenshot 2020-08-13 at 5 59 16 PM" src="https://user-images.githubusercontent.com/33023695/90122481-ec230000-dd8f-11ea-90cc-50111c7acfb9.png">

**Comment by wzhang2** [comment]
<img width="946" alt="Screenshot 2020-08-14 at 10 33 11 PM" src="https://user-images.githubusercontent.com/33023695/90262032-54e9a580-de80-11ea-8ca0-6649f0ef004e.png">
im getting this exception on android only, could this be related?

**Comment by wzhang2** [comment]
i tried to use useCDN and useSSL as well, none of the combinations works

**Comment by wzhang2** [comment]
@sebastianbochan can you please help to see what im missing here?

**Comment by wzhang2** [comment]
this was a library version issue with uimodules

**Comment by sebastianbochan** [comment]
Thank you for the feedback.

We always recommend to use the up-to-date versions (or declared in the `package.json`)
