### ISSUE TITLE
how do I disable the scroll bar on actual android devices?

### ISSUE THREAD

**Issue by wzhang2** [highcharts/highcharts-react-native#98]
it seems like the chart is not stretched out to fit the height when I test it on an android phone, and a scroll bar is always present with the chart cutoff, but I don't see it on the iOS nor android simulators, and its also fine on an actual iOS device. I tried to set scrollBar: {enabled: false} in the chart options, but that is also not helping

   <HighchartsReactNative
            styles={{
        backgroundColor: '#fff',
        height: 300,
        justifyContent: 'center',
    }}
            options={options}
            loader={true}
            modules={modules}
        />

and if I set the height as a percentage, the chart won't show up

![image](https://user-images.githubusercontent.com/33023695/90502509-84e6c080-e180-11ea-9c84-d0fef7ed1952.jpeg)

**Comment by sebastianbochan** [comment]
What is the size of a wrapper (i.e View) around the `<HighchartsReactNative />`

It looks like wrapper is higher (300px) than parent element.

**Comment by wzhang2** [comment]
thanks i figures that out @sebastianbochan
